# ~/.config/matugen/templates/colors.sh
# Shell-sourceable color variables generated by matugen.
# Source this file in scripts or have Quickshell read it to get the current accent.
# Generated by: matugen image <path>

# Primary accent — this is the main dynamic color used for borders, highlights,
# and gauge fills. It replaces the Lavender fallback everywhere.
export MATUGEN_ACCENT="#aec6ff"
export MATUGEN_ON_ACCENT="#112f60"

# Secondary / supporting accent
export MATUGEN_SECONDARY="#bfc6dc"
export MATUGEN_TERTIARY="#debcdf"

# Surface colors (these are typically close to Catppuccin Mocha Base;
# they are provided here for completeness but base/surface/text values
# in configs should remain hardcoded Catppuccin Mocha values, not these).
export MATUGEN_SURFACE="#111318"
export MATUGEN_ON_SURFACE="#e2e2e9"
export MATUGEN_BACKGROUND="#111318"

# Source color (the dominant color extracted from the wallpaper — useful for
# debugging or building a color preview in the wallpaper picker).
export MATUGEN_SOURCE="#1d7bfc"
