gui:
  theme:
    activeBorderColor:
      - '#cba4f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#cba4f7'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#cba4f7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
