animations {
	enabled = true

	bezier = floaty, 0.05, 0.09, 0.1, 1.05
	bezier = smoothOut, 0.36, 0, 0.66, -0.56
	bezier = smoothIn, 0.25, 1, 0.5, 1

	animation = windows, 1, 5, smoothIn, popin
	animation = windowsOut, 1, 5, smoothOut, popin
	animation = windowsMove, 1, 4, floaty
	animation = workspaces, 1, 6, floaty, slide
	animation = fadeIn, 1, 5, smoothIn
	animation = fadeOut, 1, 5, smoothOut
	animation = border, 1, 8, default
	animation = borderangle, 1, 30, default, loop
} 
