exec-once = awww-daemon
exec-once = bash -c '[ -f ~/.cache/current_wallpaper ] && ~/.config/hypr/scripts/wallpaper-change.sh "$(cat ~/.cache/current_wallpaper)"'
exec-once = quickhell
exec-once = hypridle
exec-once = swaync
exec-once = udiskie --tray
exec-once = systemctl --user start hyperpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
