# Floating windows
windowrule = float, class:(pavucontrol)
windowrule = center, class:(pavucontrol)
windowrule = float, class:(blueman-manager)
windowrule = center, class:(blueman-manager)
windowrule = float, class:(org.gnome.Calculator)
windowrule = center, class:(org.gnome.Calculator)

# Workspace assignments
windowrule = workspace 2, class:(brave-browser)
windowrule = workspace 4, class:(discord)
