# ~/.config/matugen/templates/colors.sh
# Shell-sourceable color variables generated by matugen.
# Source this file in scripts or have Quickshell read it to get the current accent.
# Generated by: matugen image <path>

# Primary accent — this is the main dynamic color used for borders, highlights,
# and gauge fills. It replaces the Lavender fallback everywhere.
export MATUGEN_ACCENT="{{ colors.primary.default.hex }}"
export MATUGEN_ON_ACCENT="{{ colors.on_primary.default.hex }}"

# Secondary / supporting accent
export MATUGEN_SECONDARY="{{ colors.secondary.default.hex }}"
export MATUGEN_TERTIARY="{{ colors.tertiary.default.hex }}"

# Surface colors (these are typically close to Catppuccin Mocha Base;
# they are provided here for completeness but base/surface/text values
# in configs should remain hardcoded Catppuccin Mocha values, not these).
export MATUGEN_SURFACE="{{ colors.surface.default.hex }}"
export MATUGEN_ON_SURFACE="{{ colors.on_surface.default.hex }}"
export MATUGEN_BACKGROUND="{{ colors.background.default.hex }}"

# Source color (the dominant color extracted from the wallpaper — useful for
# debugging or building a color preview in the wallpaper picker).
export MATUGEN_SOURCE="{{ colors.source_color.default.hex }}"
